import Head from 'next/head';
import Button from '../components/button/Button';
import { mockButtonProps } from '../components/button/Button.mocks';
import CatCard from '../components/cards/cat/CatCard';
import { mockCatCardProps } from '../components/cards/cat/CatCard.mocks';
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout';

import { NextPageWithLayout } from './page';
export async function getStaticProps({ locale }: any) {
  let greeting =
    locale === 'en-US'
      ? 'Hello world'
      : locale === 'de'
      ? 'hallo welt'
      : locale === 'fr'
      ? 'Bonjour le monde'
      : '';

  return {
    props: {
      greeting: greeting,
    },
  };
}
const Home: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button {...mockButtonProps.button} />
      <CatCard {...mockCatCardProps.card} />
    </div>
  );
};

export default Home;

Home.getLayout = (page: any) => {
  return <PrimaryLayout>{page}</PrimaryLayout>;
};
